// src/lib/report/opportunityLibrary.ts

import { UseCaseItem } from "./types";

export const AI_OPPORTUNITY_LIBRARY: Omit<UseCaseItem, "id">[] = [
  {
    name: "AI Proposal & RFP Generator",
    department: "Sales & Marketing",
    businessProblem: "Creating technical proposals and RFP responses takes 15-25 hours per bid with inconsistent formatting.",
    proposedSolution: "RAG-powered AI solution that scans past winning bids, company case studies, and pricing models to generate customized RFP drafts in minutes.",
    businessValueScore: 88,
    implementationEffortScore: 35,
    category: "Quick Win",
    estimatedRoiPercentage: 380,
    estimatedTimelineWeeks: 6,
    techStack: ["LLM API", "Vector Database", "Docx/PDF API", "CRM Integration"],
    expectedSavings: "1,200 hours/year (approx. ₹35 Lakhs)",
    complexity: "Low",
    priority: 1,
  },
  {
    name: "Intelligent Invoice & Receipt Processing",
    department: "Finance & Accounting",
    businessProblem: "Manual entry of vendor invoices leads to processing delays, errors, and missed early payment discounts.",
    proposedSolution: "Multimodal Vision AI to automatically extract line items, match PO numbers with ERP records, and queue payments for approval.",
    businessValueScore: 85,
    implementationEffortScore: 40,
    category: "Quick Win",
    estimatedRoiPercentage: 310,
    estimatedTimelineWeeks: 5,
    techStack: ["Vision LLM", "OCR", "ERP Connector (SAP/Tally/Oracle)"],
    expectedSavings: "₹28 Lakhs/year in labor & fee reductions",
    complexity: "Low",
    priority: 2,
  },
  {
    name: "Enterprise Knowledge & Policy Assistant",
    department: "Human Resources",
    businessProblem: "Employees spend 3+ hours per week searching SharePoint and PDF handbooks for policy and benefit answers.",
    proposedSolution: "Conversational AI assistant trained on internal HR docs, company SOPs, and IT guidelines with strict role-based access control.",
    businessValueScore: 80,
    implementationEffortScore: 30,
    category: "Quick Win",
    estimatedRoiPercentage: 270,
    estimatedTimelineWeeks: 4,
    techStack: ["Vector DB", "Embeddings", "Slack/Teams Integration"],
    expectedSavings: "800 hours/year across staff",
    complexity: "Low",
    priority: 3,
  },
  {
    name: "AI Customer Support Co-Pilot",
    department: "Customer Service",
    businessProblem: "High agent burnout and long resolution times for repetitive tier-1 customer inquiries.",
    proposedSolution: "AI Agent that auto-suggests context-aware responses to support agents and autonomously handles routine ticket resolutions.",
    businessValueScore: 82,
    implementationEffortScore: 45,
    category: "Quick Win",
    estimatedRoiPercentage: 290,
    estimatedTimelineWeeks: 6,
    techStack: ["Zendesk/Freshdesk API", "LLM", "Sentiment Analysis"],
    expectedSavings: "40% reduction in average resolution time",
    complexity: "Medium",
    priority: 4,
  },
  {
    name: "Predictive Supply Chain & Inventory Optimizer",
    department: "Operations & Logistics",
    businessProblem: "Overstocking and stockouts due to reliance on historical static spreadsheets rather than dynamic demand forecasting.",
    proposedSolution: "Machine Learning demand forecasting model integrated with real-time sales velocity and supplier lead time data.",
    businessValueScore: 92,
    implementationEffortScore: 75,
    category: "Strategic Bet",
    estimatedRoiPercentage: 420,
    estimatedTimelineWeeks: 12,
    techStack: ["Time Series Forecasting", "Python ML", "Data Lakehouse"],
    expectedSavings: "18% reduction in working capital holding costs",
    complexity: "High",
    priority: 5,
  },
  {
    name: "Automated Code Review & Security Auditor",
    department: "Engineering & IT",
    businessProblem: "Senior developers spend significant time conducting basic code reviews and checking for compliance vulnerabilities.",
    proposedSolution: "Custom LLM static analysis bot integrated into CI/CD pipelines to flag security flaws and enforce architectural standards.",
    businessValueScore: 78,
    implementationEffortScore: 35,
    category: "Quick Win",
    estimatedRoiPercentage: 240,
    estimatedTimelineWeeks: 4,
    techStack: ["GitHub Actions", "Code LLM", "SonarQube Integration"],
    expectedSavings: "₹22 Lakhs/year in dev productivity",
    complexity: "Low",
    priority: 6,
  },
  {
    name: "AI Legal Contract Review & Risk Analyzer",
    department: "Legal & Compliance",
    businessProblem: "Contract reviews by internal legal teams take 5-7 business days per vendor agreement.",
    proposedSolution: "AI contract review engine that highlights non-standard clauses, indemnification risks, and suggests standardized legal redlines.",
    businessValueScore: 84,
    implementationEffortScore: 50,
    category: "Quick Win",
    estimatedRoiPercentage: 320,
    estimatedTimelineWeeks: 6,
    techStack: ["Legal LLM", "Word Add-in", "Contract Repository"],
    expectedSavings: "70% faster contract cycle time",
    complexity: "Medium",
    priority: 7,
  },
  {
    name: "Lead Scoring & Intent Analytics Agent",
    department: "Sales & Marketing",
    businessProblem: "Sales teams waste time calling unqualified leads while high-intent prospects drop off.",
    proposedSolution: "AI intent tracking system that analyzes buyer behavior, email responses, and firmographic data to rank leads dynamically.",
    businessValueScore: 86,
    implementationEffortScore: 40,
    category: "Quick Win",
    estimatedRoiPercentage: 350,
    estimatedTimelineWeeks: 5,
    techStack: ["HubSpot/Salesforce API", "Predictive Scoring Engine"],
    expectedSavings: "25% increase in lead-to-opportunity conversion",
    complexity: "Low",
    priority: 8,
  }
];

export function getMatchingSeedUseCases(
  industry: string,
  lowScoringSections: string[],
  topPainPoints: string[]
): UseCaseItem[] {
  // Map seeds with unique IDs
  return AI_OPPORTUNITY_LIBRARY.map((item, idx) => ({
    ...item,
    id: `uc-${idx + 1}`,
  }));
}
