// src/lib/report/opportunityLibrary.ts

import { UseCaseItem } from "./types";

export const AI_OPPORTUNITY_LIBRARY: Omit<UseCaseItem, "id">[] = [
  // --- HORIZON 1: FOUNDATION & ANCHOR QUICK WINS (MONTHS 0-3) ---
  {
    name: "AI-Driven Automated QA Test Case Generation & Execution",
    department: "Software Engineering & QA",
    businessProblem: "Manual regression testing delays sprint releases by 48-72 hours, creating developer bottlenecks and regression bugs.",
    proposedSolution: "Autonomous agent analyzing PR code diffs to auto-generate end-to-end Playwright/Cypress tests pre-merge.",
    businessValueScore: 92,
    implementationEffortScore: 32,
    category: "Quick Win",
    estimatedRoiPercentage: 280,
    estimatedTimelineWeeks: 5,
    techStack: ["Playwright", "Tree-sitter AST", "Claude 3.5 Sonnet", "GitHub Actions"],
    expectedSavings: "₹32 Lakhs/year (1,400 engineering hours saved)",
    complexity: "Low",
    priority: 1,
    horizonWindow: "Horizon 1: Foundation (M 0-3)",
    podRequirement: "1 Dedicated Pod (AI Lead + 2 Devs + 0.5 QA)",
  },
  {
    name: "AI Proposal & Technical RFP Response Generator",
    department: "Sales & Business Development",
    businessProblem: "Drafting technical RFP bids takes 20+ hours per submission with inconsistent formatting and pricing calculations.",
    proposedSolution: "RAG-powered bid responder indexing past winning proposals, security audits, and rate cards to generate 80% drafts in minutes.",
    businessValueScore: 88,
    implementationEffortScore: 35,
    category: "Quick Win",
    estimatedRoiPercentage: 340,
    estimatedTimelineWeeks: 6,
    techStack: ["Hybrid RAG (BM25 + Vector)", "FastAPI", "Docx Generator", "Salesforce API"],
    expectedSavings: "₹38 Lakhs/year (50% faster proposal turnaround)",
    complexity: "Low",
    priority: 2,
    horizonWindow: "Horizon 1: Foundation (M 0-3)",
    podRequirement: "1 Dedicated Pod",
  },
  {
    name: "Autonomous PMO Operational Status & Flight-Deck Reporter",
    department: "Corporate Strategy & PMO",
    businessProblem: "Project managers spend Fridays manually pulling status across Jira, Slack, and Git to assemble executive slide decks.",
    proposedSolution: "Autonomous PMO agent synthesizing weekly sprint velocities, milestone blockers, and burn rates into formatted executive digests.",
    businessValueScore: 82,
    implementationEffortScore: 30,
    category: "Quick Win",
    estimatedRoiPercentage: 220,
    estimatedTimelineWeeks: 4,
    techStack: ["Jira REST API", "Slack Webhooks", "Python Orchestrator", "Google Slides API"],
    expectedSavings: "₹18 Lakhs/year (600 PM hours recovered)",
    complexity: "Low",
    priority: 3,
    horizonWindow: "Horizon 1: Foundation (M 0-3)",
    podRequirement: "1 Dedicated Pod",
  },

  // --- HORIZON 2: DEV ACCELERATION & EXPANSION (MONTHS 3-6) ---
  {
    name: "Automated AI Code Review & Security Vulnerability SAST Pipeline",
    department: "Software Engineering & Security",
    businessProblem: "Security vulnerabilities and non-standard API designs slip into production due to senior developer review fatigue.",
    proposedSolution: "Inline CI/CD security bot enforcing corporate architecture rules, SAST guidelines, and secrets leakage detection.",
    businessValueScore: 86,
    implementationEffortScore: 38,
    category: "Quick Win",
    estimatedRoiPercentage: 240,
    estimatedTimelineWeeks: 6,
    techStack: ["Semgrep", "DeepSeek-Coder", "Docker", "GitLab CI"],
    expectedSavings: "₹26 Lakhs/year in avoided defect triage",
    complexity: "Low",
    priority: 4,
    horizonWindow: "Horizon 2: Dev Acceleration (M 3-6)",
    podRequirement: "1 Dedicated Pod",
  },
  {
    name: "Enterprise Employee HR Policy & Benefits Assistant",
    department: "Human Resources",
    businessProblem: "HR staff spend 35% of weekly hours answering redundant leave, health policy, and expense queries across email and Slack.",
    proposedSolution: "Conversational RAG assistant trained on internal HR docs with strict role-based access control and zero hallucinated URLs.",
    businessValueScore: 80,
    implementationEffortScore: 34,
    category: "Quick Win",
    estimatedRoiPercentage: 260,
    estimatedTimelineWeeks: 5,
    techStack: ["Vector DB", "Embedding Gateway", "Slack Bot", "Workday API"],
    expectedSavings: "₹20 Lakhs/year (850 hours returned to HR)",
    complexity: "Low",
    priority: 5,
    horizonWindow: "Horizon 2: Dev Acceleration (M 3-6)",
    podRequirement: "1 Dedicated Pod",
  },

  // --- HORIZON 3: OPERATIONAL SCALE (MONTHS 6-9) ---
  {
    name: "Intelligent Multi-Modal Invoice & Vendor Document OCR Processing",
    department: "Finance & Accounting",
    businessProblem: "Processing 15,000 monthly supplier invoices involves 5 manual touches each, causing late payments and reconciliation delays.",
    proposedSolution: "Vision LLM extracting 15 line items, matching PO numbers against ERP ledgers, and routing approved batches for payment.",
    businessValueScore: 90,
    implementationEffortScore: 46,
    category: "Quick Win",
    estimatedRoiPercentage: 310,
    estimatedTimelineWeeks: 10,
    techStack: ["Vision AI", "Tesseract OCR", "SAP/Oracle Connector", "PostgreSQL"],
    expectedSavings: "₹42 Lakhs/year in labor and early-payment discounts",
    complexity: "Medium",
    priority: 6,
    horizonWindow: "Horizon 3: Operational Scale (M 6-9)",
    podRequirement: "1 Dedicated Pod + 1 Data Eng",
  },
  {
    name: "AI Legal Contract Lifecycle & Regulatory Risk Analyzer",
    department: "Legal & Compliance",
    businessProblem: "Vendor NDA and SLA contract reviews take 5-7 business days, delaying commercial vendor onboarding.",
    proposedSolution: "AI contract review engine highlighting deviations from standard indemnification terms and generating redlines.",
    businessValueScore: 84,
    implementationEffortScore: 44,
    category: "Quick Win",
    estimatedRoiPercentage: 290,
    estimatedTimelineWeeks: 8,
    techStack: ["Legal Domain LLM", "Word Add-in", "Vector Repository"],
    expectedSavings: "₹28 Lakhs/year (70% faster contract cycle time)",
    complexity: "Medium",
    priority: 7,
    horizonWindow: "Horizon 3: Operational Scale (M 6-9)",
    podRequirement: "1 Dedicated Pod",
  },
  {
    name: "Automated IT Helpdesk L1 Ticket Resolution & Provisioning Agent",
    department: "IT Operations & Cloud",
    businessProblem: "Employees wait hours for routine VPN resets, SaaS seat provisioning, and hardware access approvals.",
    proposedSolution: "Autonomous agent resolving 55% of L1 IT requests via authenticated Slack commands in sub-60 seconds.",
    businessValueScore: 83,
    implementationEffortScore: 42,
    category: "Quick Win",
    estimatedRoiPercentage: 275,
    estimatedTimelineWeeks: 7,
    techStack: ["Okta API", "Jira Service Management", "FastAPI", "Slack Bolt"],
    expectedSavings: "₹24 Lakhs/year in IT support labor",
    complexity: "Medium",
    priority: 8,
    horizonWindow: "Horizon 3: Operational Scale (M 6-9)",
    podRequirement: "1 Dedicated Pod",
  },

  // --- HORIZON 4: CX & PIPELINE AUTOMATION (MONTHS 9-12) ---
  {
    name: "Omnichannel Customer Support Agent Co-Pilot & Ticket Assist",
    department: "Customer Service & CX",
    businessProblem: "High tier-1 ticket volume causes long resolution times and frontline agent burnout during peak volume spikes.",
    proposedSolution: "In-line Agent Co-Pilot auto-drafting responses from past ticket resolutions for human one-click review and send.",
    businessValueScore: 87,
    implementationEffortScore: 48,
    category: "Quick Win",
    estimatedRoiPercentage: 295,
    estimatedTimelineWeeks: 12,
    techStack: ["Zendesk API", "Freshdesk", "Hybrid RAG", "Sentiment Telemetry"],
    expectedSavings: "₹36 Lakhs/year (40% reduction in AHT)",
    complexity: "Medium",
    priority: 9,
    horizonWindow: "Horizon 4: CX & Pipeline (M 9-12)",
    podRequirement: "1 Dedicated Pod + Support Lead",
  },
  {
    name: "Predictive Lead Scoring & Multi-Touch Attribution Engine",
    department: "Sales & Marketing",
    businessProblem: "Sales reps waste time prospecting unqualified leads while high-intent inbound inquiries go cold.",
    proposedSolution: "Machine learning intent tracker scoring leads based on email velocity, website behavior, and firmographic signals.",
    businessValueScore: 89,
    implementationEffortScore: 45,
    category: "Quick Win",
    estimatedRoiPercentage: 350,
    estimatedTimelineWeeks: 10,
    techStack: ["Salesforce CRM", "HubSpot API", "Scikit-learn", "Snowflake"],
    expectedSavings: "₹45 Lakhs/year in pipeline conversion uplift (+22%)",
    complexity: "Medium",
    priority: 10,
    horizonWindow: "Horizon 4: CX & Pipeline (M 9-12)",
    podRequirement: "1 Dedicated Pod",
  },
  {
    name: "Automated Marketing Content Engine & Campaign Localization",
    department: "Marketing & Growth",
    businessProblem: "Creating localized ad copy and content variants across multiple regional languages and personas requires 80+ hours weekly.",
    proposedSolution: "Brand-aligned generative content engine synthesizing 50+ validated ad variants with automated brand compliance checks.",
    businessValueScore: 81,
    implementationEffortScore: 36,
    category: "Quick Win",
    estimatedRoiPercentage: 230,
    estimatedTimelineWeeks: 6,
    techStack: ["Claude 3.5 Sonnet", "Figma API", "Meta Ads API", "Next.js"],
    expectedSavings: "₹20 Lakhs/year in external agency fees",
    complexity: "Low",
    priority: 11,
    horizonWindow: "Horizon 4: CX & Pipeline (M 9-12)",
    podRequirement: "1 Dedicated Pod",
  },

  // --- HORIZON 5: STRATEGIC ENTERPRISE BETS (MONTHS 12-18) ---
  {
    name: "Enterprise Knowledge Graph & Cross-Repo Developer Search Engine",
    department: "Engineering & IT",
    businessProblem: "Engineers lose 4 hours weekly searching siloed repos, Confluence wikis, and Slack threads for architectural patterns.",
    proposedSolution: "Unified hybrid vector + knowledge graph search engine delivering instant verified code snippets and system diagrams.",
    businessValueScore: 94,
    implementationEffortScore: 68,
    category: "Strategic Bet",
    estimatedRoiPercentage: 360,
    estimatedTimelineWeeks: 20,
    techStack: ["Neo4j", "Qdrant Vector DB", "LangGraph", "FastAPI"],
    expectedSavings: "₹65 Lakhs/year in recovered developer velocity",
    complexity: "High",
    priority: 12,
    horizonWindow: "Horizon 5: Strategic Bets (M 12-18)",
    podRequirement: "2 Parallel Pods (Lead Architect + 4 Devs + 2 Data Engs)",
  },
  {
    name: "Dynamic Price Optimization & Margin Analytics Engine",
    department: "Finance & Strategy",
    businessProblem: "Pricing models rely on static quarterly spreadsheets, failing to capture raw material fluctuations and competitor changes.",
    proposedSolution: "Real-time algorithmic pricing engine simulating demand elasticity and margin impact across product lines.",
    businessValueScore: 91,
    implementationEffortScore: 65,
    category: "Strategic Bet",
    estimatedRoiPercentage: 380,
    estimatedTimelineWeeks: 18,
    techStack: ["Python ML", "TimescaleDB", "ERP Pricing Connector", "PowerBI"],
    expectedSavings: "₹55 Lakhs/year in captured margin leakage",
    complexity: "High",
    priority: 13,
    horizonWindow: "Horizon 5: Strategic Bets (M 12-18)",
    podRequirement: "2 Parallel Pods",
  },
  {
    name: "Natural Language Text-to-SQL Enterprise BI Query Agent",
    department: "Data & Analytics",
    businessProblem: "Business managers submit 50+ ad-hoc SQL query requests weekly, creating a 2-week backlog for data analysts.",
    proposedSolution: "Semantic data agent allowing non-technical managers to query the data warehouse via natural English with SQL validation.",
    businessValueScore: 86,
    implementationEffortScore: 58,
    category: "Strategic Bet",
    estimatedRoiPercentage: 310,
    estimatedTimelineWeeks: 14,
    techStack: ["Vanna AI / LangChain", "Snowflake", "Databricks", "Slack Bot"],
    expectedSavings: "₹34 Lakhs/year (65% reduction in ad-hoc query backlog)",
    complexity: "Medium",
    priority: 14,
    horizonWindow: "Horizon 5: Strategic Bets (M 12-18)",
    podRequirement: "1 Dedicated Pod + 1 Data Eng",
  },
  {
    name: "Predictive Supply Chain Demand & Inventory Lead-Time Optimizer",
    department: "Operations & Logistics",
    businessProblem: "Buffer stock over-allocations and sudden component stockouts tie up working capital in static warehouses.",
    proposedSolution: "Time-series forecasting model balancing real-time sales pipeline velocity against international supplier shipping times.",
    businessValueScore: 93,
    implementationEffortScore: 72,
    category: "Strategic Bet",
    estimatedRoiPercentage: 410,
    estimatedTimelineWeeks: 22,
    techStack: ["Prophet ML", "Kafka Data Streams", "SAP S/4HANA", "Python"],
    expectedSavings: "₹72 Lakhs/year in reduced inventory carrying costs",
    complexity: "High",
    priority: 15,
    horizonWindow: "Horizon 5: Strategic Bets (M 12-18)",
    podRequirement: "2 Parallel Pods",
  },

  // --- HORIZON 6: AUTONOMOUS ENTERPRISE OPERATIONS (MONTHS 18-24) ---
  {
    name: "Autonomous Infrastructure Monitoring & Self-Healing SRE Ops",
    department: "IT Operations & Cloud",
    businessProblem: "Production incidents require manual triage across logs, Datadog metrics, and runbooks, risking client SLA penalties.",
    proposedSolution: "Autonomous agent correlating telemetry across server clusters, diagnosing root causes, and executing verified remediation runbooks.",
    businessValueScore: 95,
    implementationEffortScore: 78,
    category: "Strategic Bet",
    estimatedRoiPercentage: 420,
    estimatedTimelineWeeks: 26,
    techStack: ["OpenTelemetry", "Kubernetes Operator", "Datadog API", "Ansible"],
    expectedSavings: "₹85 Lakhs/year in avoided downtime and on-call toil",
    complexity: "High",
    priority: 16,
    horizonWindow: "Horizon 6: Autonomous Ops (M 18-24)",
    podRequirement: "2 Dedicated SRE Pods + Client SRE Leads",
  },
  {
    name: "Automated Supplier Contract Audit & Spend Leakage Detector",
    department: "Procurement",
    businessProblem: "Inconsistent vendor rate-cards and uncoordinated departmental purchasing cause 3-5% unnecessary spend leakage.",
    proposedSolution: "Continuous AI audit tool scanning vendor contracts and purchase orders to flag duplicate rates and unauthorized discounts.",
    businessValueScore: 85,
    implementationEffortScore: 52,
    category: "Strategic Bet",
    estimatedRoiPercentage: 300,
    estimatedTimelineWeeks: 12,
    techStack: ["OCR Engine", "Python NLP", "ERP Purchase History"],
    expectedSavings: "₹38 Lakhs/year in recovered spend",
    complexity: "Medium",
    priority: 17,
    horizonWindow: "Horizon 6: Autonomous Ops (M 18-24)",
    podRequirement: "1 Dedicated Pod",
  },

  // --- YEAR 2 STRATEGIC BACKLOG CANDIDATES ---
  {
    name: "AI Talent Acquisition & Automated Resume Skills Screening",
    department: "Human Resources",
    businessProblem: "Technical recruiters spend 20 hours per role reviewing 400+ applicant CVs with high subjective bias.",
    proposedSolution: "Objective semantic matching engine screening candidates against technical criteria with strict anti-bias guardrails.",
    businessValueScore: 76,
    implementationEffortScore: 48,
    category: "Long-term Fill",
    estimatedRoiPercentage: 210,
    estimatedTimelineWeeks: 10,
    techStack: ["Greenhouse / Lever API", "Embeddings", "FastAPI"],
    expectedSavings: "₹22 Lakhs/year in recruiting speed",
    complexity: "Medium",
    priority: 18,
    horizonWindow: "Year 2 Strategic Backlog",
    podRequirement: "Deferred to Year 2",
  },
  {
    name: "Multimodal Product User Research & Transcript Synthesis Hub",
    department: "Product & R&D",
    businessProblem: "Hundreds of hours of user research recordings sit unindexed, causing product teams to repeat user discovery questions.",
    proposedSolution: "Speech-to-text transcript indexer clustering customer pain points and feature requests into actionable product backlogs.",
    businessValueScore: 79,
    implementationEffortScore: 46,
    category: "Long-term Fill",
    estimatedRoiPercentage: 220,
    estimatedTimelineWeeks: 8,
    techStack: ["Whisper AI", "Vector Store", "Productboard Connector"],
    expectedSavings: "₹24 Lakhs/year in accelerated product cycles",
    complexity: "Low",
    priority: 19,
    horizonWindow: "Year 2 Strategic Backlog",
    podRequirement: "Deferred to Year 2",
  },
  {
    name: "Enterprise Zero-Trust PII Tokenization Reverse Proxy",
    department: "InfoSec & Privacy",
    businessProblem: "Employees using emerging AI tools risk accidental exfiltration of customer PII and sensitive source code.",
    proposedSolution: "Network-level reverse proxy intercepting LLM prompts to tokenize sensitive entities locally before cloud egress.",
    businessValueScore: 90,
    implementationEffortScore: 54,
    category: "Strategic Bet",
    estimatedRoiPercentage: 310,
    estimatedTimelineWeeks: 12,
    techStack: ["Presidio PII", "Envoy Proxy", "Redis Vault", "AWS KMS"],
    expectedSavings: "₹50 Lakhs/year in compliance risk avoidance",
    complexity: "Medium",
    priority: 20,
    horizonWindow: "Year 2 Strategic Backlog",
    podRequirement: "Dedicated InfoSec Pod",
  },
];

export function getMatchingSeedUseCases(
  industry: string,
  lowScoringSections: string[],
  topPainPoints: string[]
): UseCaseItem[] {
  // Map seeds with unique IDs and preserve full multi-horizon data
  return AI_OPPORTUNITY_LIBRARY.map((item, idx) => ({
    ...item,
    id: `uc-${idx + 1}`,
  }));
}
