-- ==============================================================================
-- SEED 62 AI DISCOVERY ASSESSMENT QUESTIONS & DEFAULTS INTO NISOLAI
-- ==============================================================================

TRUNCATE TABLE public.questions RESTART IDENTITY CASCADE;

INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (1, 'Leadership & Strategy', 1, 'What is the organization''s top-level strategic vision for AI over the next 3 years?', 'Look for specifics: Is there a formal AI roadmap? Is AI mentioned in the annual report? Who is driving it—CEO, CTO, or a dedicated CAIO?', ARRAY['AI Strategy Advisor', 'Innovation Portfolio Manager']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (2, 'Leadership & Strategy', 2, 'Who holds the ultimate decision-making authority and budget for AI investments?', 'Identify if this is the CEO, CTO, CIO, or a dedicated CAIO. Check if budget is centralized (one pool) or distributed across departments.', ARRAY['Governance Framework Setup', 'Executive Dashboard']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (3, 'Leadership & Strategy', 3, 'How does the organization currently measure the success of technology or digital transformation initiatives?', 'Probe for specific KPIs: ROI, time-to-market, efficiency gains, cost savings, or user adoption rates. Are these tracked systematically?', ARRAY['Transformation KPI Tracker', 'Value Realization Office']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (4, 'Leadership & Strategy', 4, 'Has the organization undergone any major digital transformations in the last 3 years, and if so, what were the outcomes?', 'Understand their change appetite. Did they succeed? Fail? What were the cultural impacts? This reveals their readiness for AI-led change.', ARRAY['Change Management Predictor', 'Legacy Migration Planner']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (5, 'Leadership & Strategy', 5, 'Is there a formal AI ethics, governance, or responsible AI policy currently in place?', 'Ask about responsible AI, bias testing, transparency requirements, and who oversees ethical AI usage.', ARRAY['AI Governance Framework', 'Bias Detection Suite']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (6, 'IT / Technology', 6, 'What is the current state of your cloud infrastructure (On-prem, Hybrid, Cloud-native)?', 'Assess maturity: Are they lifting-and-shifting legacy apps, or building cloud-native microservices? Do they use containers (Docker/K8s)?', ARRAY['Cloud Optimization Agent', 'Application Modernization Planner']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (7, 'IT / Technology', 7, 'How mature is your API ecosystem and system integration capability?', 'Do they have an API gateway? Are systems tightly coupled (point-to-point) or loosely coupled (event-driven)?', ARRAY['API Discovery & Governance', 'Integration Accelerator']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (8, 'IT / Technology', 8, 'What does your current software development lifecycle (SDLC) and DevOps velocity look like?', 'Probe for deployment frequency, lead time for changes, mean time to recovery (MTTR). Do they practice CI/CD?', ARRAY['DevOps Assistant', 'CI/CD Pipeline Optimizer']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (9, 'IT / Technology', 9, 'What are the top 3 legacy systems or technical debts that are currently constraining your business?', 'Identify mainframe, outdated ERPs, or custom monolithic code that hinders AI adoption and integration.', ARRAY['Legacy Modernization Copilot', 'Technical Debt Analyzer']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (10, 'IT / Technology', 10, 'How do you currently manage vendor lock-in risk for your core technology platforms?', 'Are there open-source alternatives? Are their contracts flexible? Do they have a multi-cloud or hybrid strategy?', ARRAY['Vendor Risk Intelligence', 'Multi-Cloud Strategy Planner']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (11, 'Data & Analytics', 11, 'How do you currently handle data quality monitoring? Who is responsible, and what tools are used?', 'Probe: Is it proactive (automated) or reactive (manual checks)? Do they have data stewards? Are there data quality SLAs?', ARRAY['Data Quality Monitor', 'Data Profiling Agent']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (12, 'Data & Analytics', 12, 'Is there a centralized data warehouse/lake, or are systems siloed?', 'Determine the existence of a Single Source of Truth (SSOT). Are data pipelines ETL/ELT? Do they use tools like Snowflake, BigQuery, or Databricks?', ARRAY['Data Fabric Architect', 'Data Lakehouse Builder']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (13, 'Data & Analytics', 13, 'How mature is your Master Data Management (MDM) for critical entities (e.g., Customer, Product, Supplier)?', 'Are customer IDs consistent across Sales, Support, and Billing? Is there a golden record?', ARRAY['MDM Harmonization Tool', 'Entity Resolution AI']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (14, 'Data & Analytics', 14, 'What is your current BI and reporting cadence? Is it real-time, daily, or weekly?', 'Identify if decisions are made on stale data. Do they have self-service BI tools (PowerBI, Tableau) or rely on IT for every report?', ARRAY['Real-time Analytics Pipeline', 'Automated Reporting Assistant']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (15, 'Data & Analytics', 15, 'Do you have a dedicated data science or advanced analytics team, and what is their primary focus?', 'Probe for skill levels: Descriptive analytics (what happened), Predictive (what will happen), or Prescriptive (what should we do).', ARRAY['Talent Augmentation Planner', 'AI/ML Platform Setup']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (16, 'Security & Compliance', 16, 'How mature is your cybersecurity posture, and do you have a formal incident response plan?', 'Assess if they have a Security Operations Center (SOC) or rely on outsourcing. Do they conduct regular penetration testing?', ARRAY['AI Threat Intelligence', 'Automated Incident Response']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (17, 'Security & Compliance', 17, 'Which regulatory frameworks apply to you (GDPR, HIPAA, SOC2, PCI-DSS, ISO 27001), and how are they managed?', 'Are they manually audited (spreadsheets) or are controls automated with continuous compliance monitoring?', ARRAY['Compliance Automation Agent', 'Regulatory Change Tracker']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (18, 'Security & Compliance', 18, 'How do you handle Data Privacy (PII) and sensitive data discovery?', 'Is data classified at rest? Are there automated data masking or anonymization tools in place?', ARRAY['PII Discovery & Masking', 'Data Privacy Copilot']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (19, 'Security & Compliance', 19, 'What is the current process for third-party vendor security assessments?', 'Is it a manual checklist sent once a year, or is there continuous monitoring with security scores?', ARRAY['Vendor Risk Intelligence', 'Automated Security Scoring']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (20, 'Security & Compliance', 20, 'How quickly can you identify and patch newly discovered vulnerabilities in your environment?', 'Measure their Mean Time to Remediate (MTTR). Do they have automated patch management?', ARRAY['Vulnerability Prioritizer', 'Patch Automation Bot']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (21, 'Customer Service', 21, 'What is your current monthly ticket volume across all support channels?', 'Is volume growing year-over-year? What is the peak season like? This helps size AI automation opportunities.', ARRAY['AI Chatbot', 'Agent Assist Tool']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (22, 'Customer Service', 22, 'What channels do you support, and are they unified (Email, Chat, Social, Phone)?', 'Siloed channels often lead to poor experiences. Check if they have an omnichannel platform.', ARRAY['Omnichannel Routing AI', 'Unified Agent Desktop']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (23, 'Customer Service', 23, 'Do you have a self-service knowledge base, and how is it maintained?', 'Is it static PDFs or a dynamic, searchable wiki? Is it integrated with their ticketing system?', ARRAY['Knowledge Assistant', 'Self-Service Optimizer']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (24, 'Customer Service', 24, 'How do you currently measure CSAT/NPS, and what is the average response and resolution time?', 'Identify automation opportunities in post-call surveys and sentiment analysis.', ARRAY['Sentiment Analysis Engine', 'Predictive CSAT Analyzer']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (25, 'Sales', 25, 'How mature is your CRM system, and how accurate is your sales forecasting?', 'Compare forecast vs. actuals over the last 4 quarters. Is forecasting done by AI/ML or purely sales rep intuition?', ARRAY['Forecasting Intelligence', 'Deal Risk Predictor']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (26, 'Sales', 26, 'How are proposals, quotes, and contracts currently generated?', 'Is it manual (copy-paste from Word) or automated via a CPQ (Configure, Price, Quote) system?', ARRAY['Proposal Generator', 'CPQ (Configure Price Quote) AI']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (27, 'Sales', 27, 'How do you prioritize leads and account scoring?', 'Are they using BANT, CHAMP, or purely manual intuition? Is there a lead scoring model?', ARRAY['Lead Scoring AI', 'Next-Best-Action Recommender']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (28, 'Sales', 28, 'Where are the biggest friction points in your sales cycle?', 'Look for bottlenecks: legal review, compliance, pricing approvals, or lengthy procurement processes.', ARRAY['Sales Cycle Optimizer', 'Deal Acceleration AI']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (29, 'Marketing', 29, 'How do you currently personalize digital content for different customer segments?', 'Is it dynamic in real-time (based on behavior) or static generic messaging sent to everyone?', ARRAY['Content Personalization AI', 'Segmentation Engine']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (30, 'Marketing', 30, 'What automation tools do you use for ad buying (PPC/Programmatic) and SEO?', 'Are campaigns optimized manually daily or algorithmically via AI bidding?', ARRAY['Ad Optimizer', 'SEO Content Generator']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (31, 'Marketing', 31, 'How is marketing attribution (touchpoint tracking) currently handled?', 'Challenges with multi-channel attribution are common. Are they using last-click, multi-touch, or algorithmic attribution?', ARRAY['Multi-Touch Attribution AI', 'Customer Journey Mapping']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (32, 'Marketing', 32, 'What is the process for creating and distributing new marketing collateral?', 'Is there a review bottleneck? Are they using DAM (Digital Asset Management) tools?', ARRAY['Creative Asset Generator', 'Marketing Calendar AI']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (33, 'Operations & Supply Chain', 33, 'How automated are your core operational processes (e.g., order-to-cash, procure-to-pay)?', 'Identify manual handoffs between departments. Count the number of times a human touches a process.', ARRAY['Process Mining AI', 'Robotic Process Automation (RPA) Spotter']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (34, 'Operations & Supply Chain', 34, 'How do you currently manage inventory, warehousing, or logistics visibility?', 'For manufacturing: IoT sensors on machines. For retail: SKU-level tracking. For logistics: fleet tracking GPS.', ARRAY['Inventory Optimizer', 'Predictive Maintenance (Mfg)']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (35, 'Operations & Supply Chain', 35, 'How do you collaborate with suppliers and manage disruptions?', 'Probe for visibility into tier-2/tier-3 suppliers. Are they using supplier portals or email/Excel?', ARRAY['Supply Chain Risk Radar', 'Supplier Collaboration Portal']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (36, 'Operations & Supply Chain', 36, 'What is your biggest operational bottleneck causing delays or cost overruns?', 'Note: Is it labor shortages, machine downtime, shipping delays, or quality issues?', ARRAY['Bottleneck Analysis AI', 'Operational Efficiency Copilot']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (37, 'Finance', 37, 'How are invoices received, processed, and approved in your accounts payable team?', 'Count the number of manual touches. Are they using OCR for invoice extraction? What is the approval workflow?', ARRAY['Invoice Intelligence', 'Automated AP Processing']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (38, 'Finance', 38, 'How long does your monthly/quarterly financial close and reconciliation process take?', 'Speed of close indicates data integration maturity. Are they using spreadsheets for consolidation?', ARRAY['Financial Close Automation', 'Reconciliation AI']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (39, 'Finance', 39, 'How do you handle Financial Planning & Analysis (FP&A) and forecasting?', 'Are spreadsheets still heavily used? Is there a dedicated FP&A tool?', ARRAY['FP&A Copilot', 'Predictive Budgeting AI']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (40, 'Finance', 40, 'What is your current approach to fraud detection and transaction monitoring?', 'Is it rule-based (static), or is there ML detection for anomalies?', ARRAY['Fraud Detection AI', 'Anomaly Monitoring System']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (41, 'HR', 41, 'How is recruitment sourcing, screening, and onboarding currently managed?', 'Assess volume of resumes processed manually. Is there an ATS (Applicant Tracking System)?', ARRAY['Resume Screening AI', 'Recruiter Copilot']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (42, 'HR', 42, 'How are Learning & Development (L&D) courses and training delivered and tracked?', 'Are they personalized? Is completion tracked? Do they have an LMS (Learning Management System)?', ARRAY['L&D Recommender', 'Skills Gap Analyzer']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (43, 'HR', 43, 'What tools support employee engagement and attrition tracking?', 'Can they predict high-risk departures? Do they conduct pulse surveys?', ARRAY['Attrition Predictor', 'Engagement Sentiment Analyzer']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (44, 'HR', 44, 'How are performance reviews and goal-setting (OKRs) managed across teams?', 'Is it an annual pain point or continuous feedback? Is there a tool?', ARRAY['Performance Insight AI', 'Goal Alignment Tracker']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (45, 'Procurement', 45, 'How do you identify, evaluate, and onboard new suppliers?', 'Is it manual or digital? Do they use a supplier discovery platform?', ARRAY['Sourcing Automation', 'Supplier Discovery AI']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (46, 'Procurement', 46, 'How are procurement contracts managed throughout their lifecycle?', 'Are they in a CLM (Contract Lifecycle Management) system or scattered drives and emails?', ARRAY['Contract Lifecycle Management (CLM) AI', 'Obligation Tracker']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (47, 'Procurement', 47, 'How do you track and benchmark supplier performance against SLAs?', 'Quantitative (scorecards, dashboards) or anecdotal? Is data shared back with suppliers?', ARRAY['Supplier Scorecard AI', 'Performance Analytics']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (48, 'Legal', 48, 'What is the volume of contracts, NDAs, and legal documents reviewed weekly?', 'High volume suggests AI contract review. What is the current average turnaround time?', ARRAY['Contract Review AI', 'NDA Analyzer']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (49, 'Legal', 49, 'How does the legal team stay on top of changes in relevant regulations?', 'Manual monitoring (trade journals, regulators) or automated alerts (regulatory intelligence platforms)?', ARRAY['Regulatory Monitoring AI', 'Regulatory Change Impact Analysis']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (50, 'Legal', 50, 'How are legal holds, e-discovery, and litigation support currently handled?', 'Probe for data retrieval times. Is there a dedicated e-discovery tool?', ARRAY['E-Discovery Assistant', 'Legal Hold Automation']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (51, 'Knowledge Management', 51, 'How do employees currently search for internal documents and expertise?', 'Is there a company wiki or intranet, and is it effective? Or do they rely on asking colleagues?', ARRAY['Enterprise Search AI', 'Internal Wiki GPT']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (52, 'Knowledge Management', 52, 'How are standard operating procedures (SOPs) and best practices captured and updated?', 'Are they living documents (version-controlled, searchable) or dusty PDFs in a shared drive?', ARRAY['SOP Generator', 'Knowledge Base Health Monitor']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (53, 'Knowledge Management', 53, 'What happens when a new employee needs to find technical knowledge to solve a problem?', 'Do they ask a colleague (tribal knowledge) or search a system? This reveals knowledge silos.', ARRAY['Expertise Location AI', 'Contextual Knowledge Assistant']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (54, 'Project Management', 54, 'How does the PMO track resource allocation and capacity planning across projects?', 'Is it spreadsheets or enterprise PPM (Project Portfolio Management) tools like Jira, Asana, or MS Project?', ARRAY['Resource Optimizer', 'Capacity Planning AI']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (55, 'Project Management', 55, 'What is the current project delivery predictability (e.g., on-time/on-budget rate)?', 'Track the variance percentage. Do you have a standard delivery methodology?', ARRAY['Delivery Risk Predictor', 'Project Health Dashboard']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (56, 'Project Management', 56, 'How are project status reports, meeting minutes, and action items generated?', 'Is the PM writing them manually from multiple emails and Slack threads, or is there a tool?', ARRAY['Status Report Generator', 'Meeting Intelligence Assistant']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (57, 'Culture & Change', 57, 'How would you describe the overall data-driven culture of your organization?', 'Do leaders make decisions based on data/evidence or primarily on intuition? Is data literacy widespread?', ARRAY['Culture Change Navigator', 'Digital Fluency Assessment']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (58, 'Culture & Change', 58, 'What is the level of AI literacy among your leadership and middle management?', 'Have they had AI training or workshops? Do they understand basic AI concepts?', ARRAY['AI Literacy Bootcamp', 'Leadership AI Workshop Planner']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (59, 'Culture & Change', 59, 'How does the organization handle failure and risk-taking regarding new technologies?', 'Is it a ''fail fast, learn fast'' culture, or is it highly risk-averse?', ARRAY['Innovation Sandbox Planner', 'Risk-Tolerance Assessment']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (60, 'Culture & Change', 60, 'What are the primary barriers to change you foresee in adopting AI?', 'Top answers: Fear of job loss, lack of trust in AI, unclear business value, or lack of technical skills.', ARRAY['Change Impact Analysis', 'Stakeholder Communication Generator']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (61, 'Culture & Change', 61, 'How siloed are the departments currently?', 'Probe about cross-functional collaboration. Do teams share data and insights freely?', ARRAY['Silo Breaker Strategy', 'Cross-Functional AI Council Planner']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;
INSERT INTO public.questions (id, section, order_index, question_text, tip_discussion, triggered_patterns) VALUES (62, 'Culture & Change', 62, 'Is there a clear internal communications channel for upcoming tech changes?', 'Crucial for managing digital transformation. Do they have an internal comms plan for major tech rollouts?', ARRAY['Internal Comms AI', 'Digital Change Agent']::TEXT[]) ON CONFLICT (id) DO UPDATE SET section = EXCLUDED.section, order_index = EXCLUDED.order_index, question_text = EXCLUDED.question_text, tip_discussion = EXCLUDED.tip_discussion, triggered_patterns = EXCLUDED.triggered_patterns;

SELECT setval(pg_get_serial_sequence('public.questions', 'id'), COALESCE(max(id), 1)) FROM public.questions;

-- Revenue Range Defaults
INSERT INTO public.revenue_range_defaults (revenue_range, baseline_budget_cr, typical_timeline_months, recommended_plan) VALUES
('Under ₹50 Cr', 0.25, 3, 'Foundation'),
('₹50 - 250 Cr', 0.75, 6, 'Acceleration'),
('₹250 - 1000 Cr', 2.00, 9, 'Enterprise'),
('Above ₹1000 Cr', 5.00, 12, 'Transformation')
ON CONFLICT (revenue_range) DO NOTHING;
