// lib/ai/defaultUseCases.ts

export interface UseCaseItem {
  id: string;
  name: string;
  department: string;
  description: string;
  business_value: "High" | "Medium" | "Low";
  feasibility: "High" | "Medium" | "Low";
  estimated_roi_percentage: number;
  implementation_months: number;
  suggested_tech_stack: string[];
  estimated_savings_annual_usd: number;
}

export const DEFAULT_TOP_20_USE_CASES: UseCaseItem[] = [
  {
    id: "uc-01",
    name: "AI-Powered Omnichannel Customer Support Assistant",
    department: "Customer Service & Support",
    description: "Deploy a Retrieval-Augmented Generation (RAG) assistant integrated with enterprise KB and ticket systems to resolve tier-1 customer inquiries instantly.",
    business_value: "High",
    feasibility: "High",
    estimated_roi_percentage: 145,
    implementation_months: 3,
    suggested_tech_stack: ["LLM (GPT-4 / Gemini)", "Vector DB (Pinecone/pgvector)", "Next.js"],
    estimated_savings_annual_usd: 120000,
  },
  {
    id: "uc-02",
    name: "Predictive Maintenance & Equipment Asset Analytics",
    department: "Operations & Logistics",
    description: "Leverage real-time IoT telemetry and anomaly detection models to forecast equipment failures 48 hours in advance, reducing downtime.",
    business_value: "High",
    feasibility: "Medium",
    estimated_roi_percentage: 180,
    implementation_months: 6,
    suggested_tech_stack: ["IoT Sensors", "Time-Series ML Models", "Azure IoT Hub"],
    estimated_savings_annual_usd: 250000,
  },
  {
    id: "uc-03",
    name: "Automated Intelligent Document & Invoice Processing",
    department: "Finance & Accounting",
    description: "Automate invoice data extraction, line-item matching, and GL coding with deep learning OCR and structured LLM parsing.",
    business_value: "High",
    feasibility: "High",
    estimated_roi_percentage: 160,
    implementation_months: 3,
    suggested_tech_stack: ["OCR (Azure Form Recognizer)", "LLM Extraction", "Python"],
    estimated_savings_annual_usd: 95000,
  },
  {
    id: "uc-04",
    name: "Enterprise Knowledge Graph & Semantic Search",
    department: "IT & Engineering",
    description: "Unify internal wiki, Confluence, and codebases into an intelligent semantic search portal for enterprise knowledge discovery.",
    business_value: "Medium",
    feasibility: "High",
    estimated_roi_percentage: 130,
    implementation_months: 4,
    suggested_tech_stack: ["Neo4j", "Vector Embeddings", "LangChain"],
    estimated_savings_annual_usd: 85000,
  },
  {
    id: "uc-05",
    name: "Predictive Lead Scoring & Automated Outreach",
    department: "Sales & Marketing",
    description: "Analyze historical deal conversion signals to score incoming leads in real time and generate personalized sales follow-up drafts.",
    business_value: "High",
    feasibility: "High",
    estimated_roi_percentage: 175,
    implementation_months: 3,
    suggested_tech_stack: ["HubSpot API", "Scikit-Learn", "OpenAI API"],
    estimated_savings_annual_usd: 140000,
  },
  {
    id: "uc-06",
    name: "AI Talent Acquisition & Automated Resume Screening",
    department: "Human Resources",
    description: "Match job requirements against candidate profiles, scoring alignment while eliminating biases in preliminary candidate screening.",
    business_value: "Medium",
    feasibility: "High",
    estimated_roi_percentage: 125,
    implementation_months: 2,
    suggested_tech_stack: ["Python NLP", "FastAPI", "Workday API"],
    estimated_savings_annual_usd: 60000,
  },
  {
    id: "uc-07",
    name: "Autonomous Infrastructure Monitoring & Self-Healing Ops",
    department: "IT Operations & DevOps",
    description: "Detect system metrics anomalies early and execute autonomous self-healing runbooks before service disruptions occur.",
    business_value: "High",
    feasibility: "Medium",
    estimated_roi_percentage: 165,
    implementation_months: 5,
    suggested_tech_stack: ["Prometheus", "Anomaly Detection ML", "Kubernetes Operator"],
    estimated_savings_annual_usd: 150000,
  },
  {
    id: "uc-08",
    name: "AI Contract Lifecycle & Regulatory Audit Automation",
    department: "Legal & Compliance",
    description: "Automatically review vendor contracts for non-standard terms, liability risks, and compliance with GDPR/HIPAA standards.",
    business_value: "High",
    feasibility: "Medium",
    estimated_roi_percentage: 140,
    implementation_months: 4,
    suggested_tech_stack: ["Claude 3.5 Sonnet", "NLP Legal Models", "React"],
    estimated_savings_annual_usd: 110000,
  },
  {
    id: "uc-09",
    name: "Computer Vision Automated Defect Inspection",
    department: "Quality Assurance & Manufacturing",
    description: "Deploy high-speed camera vision models on production lines to detect physical product defects with 99.4% precision.",
    business_value: "High",
    feasibility: "Medium",
    estimated_roi_percentage: 190,
    implementation_months: 6,
    suggested_tech_stack: ["YOLOv8", "OpenCV", "Edge AI GPU"],
    estimated_savings_annual_usd: 210000,
  },
  {
    id: "uc-10",
    name: "Dynamic Price Optimization & Margin Analytics Engine",
    department: "Finance & Strategy",
    description: "Model elasticity, demand fluctuations, and competitor pricing signals to dynamically suggest optimal product pricing tiers.",
    business_value: "High",
    feasibility: "Medium",
    estimated_roi_percentage: 155,
    implementation_months: 4,
    suggested_tech_stack: ["XGBoost", "Python", "Snowflake"],
    estimated_savings_annual_usd: 175000,
  },
  {
    id: "uc-11",
    name: "Real-Time Customer Churn Prediction & Retention Workflows",
    department: "Customer Success",
    description: "Identify high-risk customer accounts based on platform usage drop-offs and automatically trigger proactive retention plays.",
    business_value: "High",
    feasibility: "High",
    estimated_roi_percentage: 150,
    implementation_months: 3,
    suggested_tech_stack: ["Random Forest ML", "Segment CDP", "Webhooks"],
    estimated_savings_annual_usd: 135000,
  },
  {
    id: "uc-12",
    name: "Generative AI Code & Architecture Assistant",
    department: "Software Engineering",
    description: "Equip engineering teams with fine-tuned code suggestion models adhering to internal architecture patterns and security rules.",
    business_value: "High",
    feasibility: "High",
    estimated_roi_percentage: 200,
    implementation_months: 2,
    suggested_tech_stack: ["GitHub Copilot Enterprise", "Custom RAG", "VS Code Extension"],
    estimated_savings_annual_usd: 180000,
  },
  {
    id: "uc-13",
    name: "AI Vendor Risk & Supply Chain Disruption Predictor",
    department: "Procurement & Supply Chain",
    description: "Monitor global geopolitical, financial, and weather news feeds to predict vendor supply chain bottlenecks before they impact delivery.",
    business_value: "Medium",
    feasibility: "Medium",
    estimated_roi_percentage: 135,
    implementation_months: 5,
    suggested_tech_stack: ["News API NLP", "Graph Analytics", "Streamlit"],
    estimated_savings_annual_usd: 90000,
  },
  {
    id: "uc-14",
    name: "Executive Speech-to-Text & Business Meeting Summarizer",
    department: "Executive Operations",
    description: "Record and transcribe leadership syncs, auto-extracting key action items, deadlines, and executive summaries directly into Slack/Jira.",
    business_value: "Medium",
    feasibility: "High",
    estimated_roi_percentage: 110,
    implementation_months: 1,
    suggested_tech_stack: ["Whisper API", "GPT-4o", "Slack API"],
    estimated_savings_annual_usd: 45000,
  },
  {
    id: "uc-15",
    name: "Enterprise Cyber Threat Intelligence & Anomaly Analyzer",
    department: "Information Security",
    description: "Analyze millions of auth logs and network events to identify lateral movement, credential abuse, and zero-day attack vectors.",
    business_value: "High",
    feasibility: "Medium",
    estimated_roi_percentage: 170,
    implementation_months: 4,
    suggested_tech_stack: ["SIEM (Splunk)", "Transformer Threat Models", "Python"],
    estimated_savings_annual_usd: 200000,
  },
  {
    id: "uc-16",
    name: "Personalized Customer Product Recommendation Engine",
    department: "E-Commerce / Marketing",
    description: "Deliver real-time personalized product cross-sell and up-sell suggestions based on browsing intent and historical basket analysis.",
    business_value: "High",
    feasibility: "High",
    estimated_roi_percentage: 165,
    implementation_months: 3,
    suggested_tech_stack: ["Collaborative Filtering", "Vector Similarity", "Redis"],
    estimated_savings_annual_usd: 160000,
  },
  {
    id: "uc-17",
    name: "Automated Data Governance & PII Classification",
    department: "Data Architecture",
    description: "Scan enterprise databases to discover, tag, and mask personally identifiable information (PII) to comply with privacy laws.",
    business_value: "Medium",
    feasibility: "High",
    estimated_roi_percentage: 120,
    implementation_months: 3,
    suggested_tech_stack: ["Apache Atlas", "SpaCy NLP", "PostgreSQL"],
    estimated_savings_annual_usd: 70000,
  },
  {
    id: "uc-18",
    name: "AR & AI Augmented Field Technician Copilot",
    department: "Field Operations",
    description: "Guide field engineers through complex machinery repairs using visual overlay steps and voice-controlled AI troubleshooting.",
    business_value: "Medium",
    feasibility: "Medium",
    estimated_roi_percentage: 140,
    implementation_months: 6,
    suggested_tech_stack: ["Spatial AI", "Mobile Vision SDK", "iOS/Android"],
    estimated_savings_annual_usd: 105000,
  },
  {
    id: "uc-19",
    name: "Conversational Employee HR & IT Helpdesk Bot",
    department: "People & HR",
    description: "Provide 24/7 instant answers to employee benefit queries, leave policies, and IT access requests via Slack/Teams.",
    business_value: "Medium",
    feasibility: "High",
    estimated_roi_percentage: 115,
    implementation_months: 2,
    suggested_tech_stack: ["Slack / MS Teams Bot", "RAG Engine", "ServiceNow API"],
    estimated_savings_annual_usd: 55000,
  },
  {
    id: "uc-20",
    name: "AI Market Intelligence & Competitor Tracking Portal",
    department: "Product Management & Strategy",
    description: "Automatically track competitor release notes, pricing changes, and customer reviews to distill monthly strategic benchmark briefs.",
    business_value: "Medium",
    feasibility: "High",
    estimated_roi_percentage: 130,
    implementation_months: 3,
    suggested_tech_stack: ["Web Scraping", "Summarization LLM", "Tailwind Dashboard"],
    estimated_savings_annual_usd: 80000,
  },
];
